name: Pull Request Checks

on:
  pull_request:
    branches: [development, production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Lint and format the code
        run: npm run lint && npm run format

      - name: Build the solution
        run: npm run build

      - name: Run tests
        run: npm test
